language: en
pipeline: supervised_embeddings
policies:
- name: KerasPolicy
  featurizer:
  - name: MaxHistoryTrackerFeaturizer
    max_history: 5
    state_featurizer:
    - name: BinarySingleStateFeaturizer
  epochs: 200
  validation_split: 0.2
- name: FallbackPolicy
  fallback_action_name: action_default_fallback
- name: MemoizationPolicy
  max_history: 5
